version: "3.8"
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongo'
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    restart: always
  backend:
    build: ./webapp
    ports:
      - '80:80'
    volumes:
      - ./webapp:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

volumes:
  data:
